# Service configuration for the nginx ingress controller service
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cp-ingress-ctl-svc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    agentVersion: {{ .Chart.Version }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Release.Namespace }}
    # Following two lines where added for AWS EKS deployment support
    # This switches the LoadBalancer type from CLB (default) to NLB so that predefined EIPs for the NLB deployment can be set. 
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # Replace the eipalloc-***** values below with your own eipalloc-values for the previously created EIPs
    # the number of eipalloc-... values has to match the number of subnets/AZs allocated with the ELB (typically three).
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-11111,eipalloc-22222,eipalloc-33333
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
